// EU Country wage data - Datos reales de Supabase
// Fuente: IDSC (Income Distribution and Social Comparisons) - Eurostat

// Lista de países disponibles en la base de datos (TABLE_1)
export const EU_COUNTRIES = [
  "Austria",
  "Belgium",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "France",
  "Germany",
  "Greece",
  "Ireland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Netherlands",
  "Portugal",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "United Kingdom",
];

// Ocupaciones generales (ISCO0801 - 1 dígito)
export const OCCUPATIONS = [
  "Managers",
  "Professionals",
  "Technicians and associate professionals",
  "Clerical support workers",
  "Service and sales workers",
  "Skilled agricultural, forestry and fishery workers",
  "Craft and related trades workers",
  "Plant and machine operators and assemblers",
  "Elementary occupations",
];

// Ocupaciones detalladas (ISCO0804 - 4 dígitos) - Muestra representativa
export const OCCUPATIONS_DETAILED = [
  "Accountants",
  "Accounting and bookkeeping clerks",
  "Accounting associate professionals",
  "Actors",
  "Administrative and executive secretaries",
  "Advertising and marketing professionals",
  "Agricultural and industrial machinery mechanics and repairers",
  "Applications programmers",
  "Butchers, fishmongers and related food preparers",
  "Buyers",
  "Cooks",
  "Craft and related workers not elsewhere classified",
  "Driving instructors",
  "Early childhood educators",
  "Film, stage and related directors and producers",
  "Finance managers",
  "General office clerks",
  "Health care assistants",
  "Health professionals not elsewhere classified",
  "Human resource managers",
  "Locomotive engine drivers",
  "Mail carriers and sorting clerks",
  "Management and organisation analysts",
  "Mining and metallurgical technicians",
  "Mining and quarrying labourers",
  "Mining engineers, metallurgists and related professionals",
  "Physicists and astronomers",
  "Physiotherapists",
  "Physiotherapy technicians and assistants",
  "Plastic products machine operators",
  "Product graders and testers (excluding foods and beverages)",
  "Retail and wholesale trade managers",
  "Roofers",
  "Rubber products machine operators",
  "Sales and marketing managers",
  "Senior government officials",
  "Senior officials of special-interest organisations",
  "Service station attendants",
  "Services managers not elsewhere classified",
  "Sports coaches, instructors and officials",
  "Sports, recreation and cultural centre managers",
  "Spray painters and varnishers",
  "Stall and market salespersons",
  "Stationary plant and machine operators not elsewhere classified",
  "Stock clerks",
  "Systems analysts",
  "Teaching professionals not elsewhere classified",
  "Technical and medical sales professionals (excluding ICT)",
  "Welders and flamecutters",
  "Well drillers and borers and related workers",
  "Window cleaners",
  "Wood processing plant operators",
  "Woodworking-machine tool setters and operators",
];

// Niveles educativos (EDUISCED) - Clasificación completa
export const EDUCATION_LEVELS = [
  "No education",
  "Early childhood education",
  "Primary education",
  "Primary education or 1st stage of basic education",
  "Lower secondary or 2nd stage of basic education",
  "Lower secondary or 2nd stage of basic education 2A",
  "Upper secondary education",
  "Upper secondary education 3A",
  "Upper secondary education 3C",
  "Post-secondary non-tertiary education",
  "First stage of tertiary education",
  "First stage of tertiary education 5A",
  "First stage of tertiary education 5B",
  "Second stage of tertiary education",
  "Second stage of tertiary education (leading to an advanced research qualification)",
];

// Niveles educativos simplificados (para UI)
export const EDUCATION_LEVELS_SIMPLE = [
  "No education",
  "Primary education",
  "Lower secondary education",
  "Upper secondary education",
  "Post-secondary non-tertiary",
  "First stage tertiary (Bachelor/5A/5B)",
  "Second stage tertiary (Master/Doctoral)",
];

// Sectores económicos (NACE2004) - Lista completa
export const ECONOMIC_ACTIVITIES = [
  "Accounting, bookkeeping and auditing activities; tax consultancy",
  "Activities of call centres",
  "Activities of collection agencies and credit bureaus",
  "Activities of employment placement agencies",
  "Activities of professional membership organisations",
  "Activities of religious organisations",
  "Activities of sports clubs",
  "Administration of financial markets",
  "Artistic creation",
  "Beverage serving activities",
  "Business and other management consultancy activities",
  "Buying and selling of own real estate",
  "Cargo handling",
  "Central banking",
  "Child day-care activities",
  "Combined office administrative service activities",
  "Computer consultancy activities",
  "Computer facilities management activities",
  "Computer programming activities",
  "Compulsory social security activities",
  "Construction of bridges and tunnels",
  "Construction of roads and motorways",
  "Construction of residential and non-residential buildings",
  "Data processing, hosting and related activities",
  "Defence activities",
  "Demolition and site preparation",
  "Development of building projects",
  "Distribution of electricity",
  "Electrical installation",
  "Engineering activities and related technical consultancy",
  "Extraction of crude petroleum",
  "Fitness facilities",
  "Foreign affairs",
  "Freight transport by road",
  "Fund management activities",
  "General medical practice activities",
  "General public administration activities",
  "General secondary education",
  "Growing of non-perennial crops",
  "Growing of perennial crops",
  "Hospital activities",
  "Hotels and similar accommodation",
  "Joinery installation",
  "Legal activities",
  "Maintenance and repair of motor vehicles",
  "Management of real estate on fee or contract basis",
  "Manufacture of basic metals",
  "Manufacture of basic pharmaceutical products and pharmaceutical preparations",
  "Manufacture of beverages",
  "Manufacture of chemicals and chemical products",
  "Manufacture of computer, electronic and optical products",
  "Manufacture of electrical equipment",
  "Manufacture of fabricated metal products, except machinery and equipment",
  "Manufacture of food products",
  "Manufacture of furniture",
  "Manufacture of machinery and equipment n.e.c.",
  "Manufacture of motor vehicles, trailers and semi-trailers",
  "Manufacture of other transport equipment",
  "Manufacture of rubber and plastic products",
  "Manufacture of textiles",
  "Manufacture of wearing apparel",
  "Manufacture of wood and of products of wood and cork",
  "Motion picture, video and television programme production activities",
  "Motion picture, video and television programme post-production activities",
  "Museums activities",
  "Mining of other non-ferrous metal ores",
  "Non-specialised wholesale trade",
  "Operation of sports facilities",
  "Organisation of conventions and trade shows",
  "Other accommodation",
  "Other activities auxiliary to financial services, except insurance and pension funding",
  "Other building and industrial cleaning activities",
  "Other cleaning activities",
  "Other education n.e.c.",
  "Other human health activities",
  "Other information technology and computer service activities",
  "Other manufacturing n.e.c.",
  "Other mining and quarrying n.e.c.",
  "Other monetary intermediation",
  "Other personal service activities n.e.c.",
  "Other postal and courier activities",
  "Other professional, scientific and technical activities n.e.c.",
  "Other research and experimental development on natural sciences and engineering",
  "Other software publishing",
  "Other specialised wholesale",
  "Other sports activities",
  "Performing arts",
  "Physical well-being activities",
  "Post-secondary non-tertiary education",
  "Publishing of journals and periodicals",
  "Publishing of newspapers",
  "Recovery of sorted materials",
  "Regulation of the activities of providing health care, education, cultural services and other social services",
  "Repair and installation of machinery and equipment",
  "Residential care activities for mental retardation, mental health and substance abuse",
  "Restaurants and mobile food service activities",
  "Retail sale in non-specialised stores",
  "Retail sale of automotive fuel in specialised stores",
  "Retail sale of clothing in specialised stores",
  "Retail sale of cosmetic and toilet articles in specialised stores",
  "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores",
  "Retail sale of food, beverages and tobacco in specialised stores",
  "Retail sale of footwear and leather goods in specialised stores",
  "Retail sale of furniture, lighting equipment and other household articles in specialised stores",
  "Retail sale of medical and orthopaedic goods in specialised stores",
  "Retail sale of newspapers and stationery in specialised stores",
  "Retail sale of second-hand goods in stores",
  "Retail sale of sporting equipment in specialised stores",
  "Retail sale of textiles in specialised stores",
  "Retail sale of watches and jewellery in specialised stores",
  "Retail sale via mail order houses or via Internet",
  "Retail sale via stalls and markets",
  "Retail trade of motor vehicle parts and accessories",
  "Roofing activities",
  "Sale of cars and light motor vehicles",
  "Sale of other motor vehicles",
  "Sea and coastal passenger water transport",
  "Service activities incidental to land transportation",
  "Social work activities without accommodation for the elderly and disabled",
  "Specialist medical practice activities",
  "Support activities to agriculture and post-harvest crop activities",
  "Support activities to performing arts",
  "Technical testing and analysis",
  "Television programming and broadcasting activities",
  "Temporary employment agency activities",
  "Tertiary education",
  "Test drilling and boring",
  "Tour operator activities",
  "Translation and interpretation activities",
  "Transmission of electricity",
  "Travel agency activities",
  "Trusts, funds and similar financial entities",
  "Urban and suburban passenger land transport",
  "Warehousing and storage",
  "Washing and (dry-)cleaning of textile and fur products",
  "Web portals",
  "Wholesale of food, beverages and tobacco",
  "Wholesale of household goods",
  "Wholesale of other machinery, equipment and supplies",
  "Wholesale on fee or contract basis",
  "Wholesale trade of motor vehicle parts and accessories",
  "Wired telecommunications activities",
];

// Sectores económicos agrupados (para UI simplificada)
export const ECONOMIC_SECTORS_GROUPED = [
  {
    label: "Agriculture & Farming",
    keywords: ["growing", "agricultural", "crops"],
  },
  {
    label: "Mining & Extraction",
    keywords: ["mining", "extraction", "quarrying", "drilling"],
  },
  { label: "Manufacturing", keywords: ["manufacture"] },
  {
    label: "Construction",
    keywords: ["construction", "building", "roofing", "joinery", "demolition"],
  },
  { label: "Retail & Wholesale", keywords: ["retail", "wholesale", "sale of"] },
  {
    label: "Transportation & Storage",
    keywords: ["transport", "freight", "cargo", "warehousing"],
  },
  {
    label: "Accommodation & Food",
    keywords: ["hotel", "restaurant", "beverage", "accommodation"],
  },
  {
    label: "IT & Technology",
    keywords: ["computer", "software", "programming", "data processing", "web"],
  },
  {
    label: "Finance & Insurance",
    keywords: ["banking", "financial", "fund", "insurance"],
  },
  { label: "Real Estate", keywords: ["real estate"] },
  {
    label: "Professional Services",
    keywords: ["consultancy", "legal", "accounting", "engineering"],
  },
  {
    label: "Public Administration",
    keywords: [
      "public administration",
      "government",
      "defence",
      "foreign affairs",
    ],
  },
  { label: "Education", keywords: ["education", "teaching"] },
  {
    label: "Health & Social Work",
    keywords: ["health", "hospital", "medical", "social work", "care"],
  },
  {
    label: "Arts & Entertainment",
    keywords: ["arts", "sports", "entertainment", "museums", "performing"],
  },
  {
    label: "Other Services",
    keywords: ["cleaning", "repair", "personal service"],
  },
];

// Género/Sexo
export const GENDERS = [
  "Male",
  "Female",
  "Total", // Agregado por algunos datasets
];

// Tamaños de empresa (si está disponible en los datos)
export const COMPANY_SIZES = [
  "1-9 employees",
  "10-49 employees",
  "50-249 employees",
  "250-999 employees",
  "1000+ employees",
];

// Posiciones/Niveles jerárquicos
export const POSITIONS = [
  "Entry level",
  "Junior",
  "Mid-level",
  "Senior",
  "Lead",
  "Manager",
  "Director",
  "Executive",
];

// Rangos de experiencia laboral
export const EXPERIENCE_RANGES = [
  "Less than 1 year",
  "1-2 years",
  "3-5 years",
  "6-10 years",
  "11-15 years",
  "16-20 years",
  "More than 20 years",
];

// Años disponibles en TABLE_1
export const AVAILABLE_YEARS = [2018, 2019, 2020, 2021, 2022];

// ============================================
// DATOS ESTÁTICOS DE RESPALDO (fallback)
// Usar solo si la API no responde
// ============================================

// Box-plot data aproximado por país (en miles EUR/mes) - Para fallback
export const COUNTRY_WAGE_DATA = {
  Austria: { min: 1.8, q1: 2.8, median: 3.4, q3: 4.4, max: 6.2 },
  Belgium: { min: 1.9, q1: 2.9, median: 3.5, q3: 4.5, max: 6.5 },
  Bulgaria: { min: 0.4, q1: 0.6, median: 0.9, q3: 1.3, max: 2.1 },
  Croatia: { min: 0.6, q1: 0.9, median: 1.2, q3: 1.7, max: 2.5 },
  Cyprus: { min: 0.9, q1: 1.4, median: 1.8, q3: 2.5, max: 3.8 },
  "Czech Republic": { min: 0.8, q1: 1.2, median: 1.6, q3: 2.2, max: 3.4 },
  Denmark: { min: 2.5, q1: 3.8, median: 4.5, q3: 5.5, max: 7.5 },
  Estonia: { min: 0.7, q1: 1.1, median: 1.5, q3: 2.1, max: 3.2 },
  France: { min: 1.5, q1: 2.3, median: 3.0, q3: 4.0, max: 6.0 },
  Germany: { min: 1.6, q1: 2.8, median: 3.6, q3: 4.8, max: 7.0 },
  Greece: { min: 0.6, q1: 0.9, median: 1.2, q3: 1.8, max: 2.8 },
  Ireland: { min: 2.0, q1: 3.0, median: 3.8, q3: 5.0, max: 7.2 },
  Italy: { min: 1.2, q1: 1.8, median: 2.4, q3: 3.2, max: 5.0 },
  Latvia: { min: 0.5, q1: 0.8, median: 1.1, q3: 1.6, max: 2.5 },
  Lithuania: { min: 0.5, q1: 0.9, median: 1.2, q3: 1.7, max: 2.7 },
  Luxembourg: { min: 2.5, q1: 4.0, median: 5.0, q3: 6.5, max: 9.0 },
  Malta: { min: 0.9, q1: 1.3, median: 1.7, q3: 2.3, max: 3.5 },
  Netherlands: { min: 1.8, q1: 2.8, median: 3.5, q3: 4.6, max: 6.8 },
  Portugal: { min: 0.7, q1: 1.0, median: 1.3, q3: 1.9, max: 3.0 },
  Slovakia: { min: 0.6, q1: 1.0, median: 1.3, q3: 1.8, max: 2.8 },
  Slovenia: { min: 0.9, q1: 1.4, median: 1.9, q3: 2.6, max: 3.8 },
  Spain: { min: 0.9, q1: 1.5, median: 2.0, q3: 2.8, max: 4.5 },
  Sweden: { min: 2.0, q1: 3.0, median: 3.6, q3: 4.5, max: 6.5 },
  "United Kingdom": { min: 1.8, q1: 2.6, median: 3.2, q3: 4.2, max: 6.0 },
};

// Datos históricos de ejemplo (fallback)
export const HISTORICAL_WAGE_DATA = {
  Spain: [
    { period: "2018", avg: 1.7, min: 0.8, max: 3.3 },
    { period: "2019", avg: 1.8, min: 0.8, max: 3.5 },
    { period: "2020", avg: 1.8, min: 0.8, max: 3.5 },
    { period: "2021", avg: 2.0, min: 0.9, max: 4.0 },
  ],
  Portugal: [
    { period: "2018", avg: 1.0, min: 0.5, max: 2.0 },
    { period: "2019", avg: 1.1, min: 0.6, max: 2.2 },
    { period: "2020", avg: 1.2, min: 0.6, max: 2.4 },
    { period: "2021", avg: 1.3, min: 0.7, max: 2.8 },
  ],
  Germany: [
    { period: "2018", avg: 3.2, min: 1.4, max: 5.8 },
    { period: "2019", avg: 3.3, min: 1.5, max: 6.0 },
    { period: "2020", avg: 3.4, min: 1.5, max: 6.2 },
    { period: "2021", avg: 3.6, min: 1.6, max: 7.0 },
  ],
};

// Distribución por sector (fallback)
export const SECTOR_DISTRIBUTION = {
  Spain: [
    { name: "Services", value: 762 },
    { name: "Industry", value: 658 },
    { name: "Construction", value: 740 },
    { name: "Agriculture", value: 577 },
    { name: "Technology", value: 959 },
    { name: "Public", value: 203 },
    { name: "Other", value: 93 },
    { name: "Finance", value: 315 },
  ],
  Portugal: [
    { name: "Services", value: 520 },
    { name: "Industry", value: 430 },
    { name: "Construction", value: 380 },
    { name: "Agriculture", value: 290 },
    { name: "Technology", value: 610 },
    { name: "Public", value: 180 },
    { name: "Other", value: 75 },
    { name: "Finance", value: 245 },
  ],
};
